### ISSUE TITLE
Priority Fee during this congested period.

### ISSUE THREAD

**Issue by metarsit** [gagliardetto/solana-go#193]
# Context (TLDR;)
- I am trying to improve my send function for Solana 
- With the recent transaction spike, not many of my transaction is completed
- Hoping to find a better way for this with this library

# Current code

```go
	limit := computebudget.NewSetComputeUnitLimitInstruction(500000).Build()
	feesInit := computebudget.NewSetComputeUnitPriceInstructionBuilder().
		SetMicroLamports(3000).Build()

	trf := system.NewTransferInstruction(
		bigAmt.Uint64(),
		accountFrom.PublicKey(),
		accountTo,
	).Build()

	log.Info("Creating Transaction")
	tx, err := solana.NewTransactionBuilder().
		AddInstruction(feesInit).
		AddInstruction(limit).
		AddInstruction(trf).
		SetRecentBlockHash(recent).
		SetFeePayer(accountFrom.PublicKey()).
		Build()
	if err != nil {
		return errors.Wrap(err, "unable to create new transaction")
	}
```

# Some help I may need
1. Did I use the wrong value for the limit and fee? (I followed #166)
2. Is there a better way to build this transaction before signing and sending it?

I really appreciate any help you can provide. I am pretty new to this and hope I can get a kickstart on this. Thank you very much.

**Comment by 0xvbetsun** [comment]
@metarsit IMO [official doc](https://solana.com/docs/intro/transaction_fees#prioritization-fee) and [Helius article](https://www.helius.dev/blog/priority-fees-understanding-solanas-transaction-fee-mechanics) are the best for kicking-off.

Your code looks good to me. You're trying to set the prioritization fee as `6_500` Lamports in your example.
```
500_000 * 3_000  * 0.000001 + 5_000 = 6_500
```
where:
`500_000`  - compute unit limit
`3_000`     - compute unit price
`0.000001` - convert microlLamports to Lamports
`5_000`     - base fee in Lamports


If you can't land your tx with `6_500` Lamports, current commissions may be higher due to congestion.

I'd suggest using [getrecentprioritizationfees](https://solana.com/docs/rpc/http/getrecentprioritizationfees) RPC method to understand the current market condition.  And [here](https://github.com/gagliardetto/solana-go?tab=readme-ov-file#index--rpc--getrecentprioritizationfees) is an example of the call in this SDK

**Comment by metarsit** [comment]
Thank you for a great share on the information @0xvbetsun! I understand this a bit better now. 
However, I have tried to set even crazier fee but the success rate is still very low. 
Is there any other way to improve the success rate?

**Comment by metarsit** [comment]
Thanks both! I will apply these changes! ❤️
