### ISSUE TITLE
Problem with getting token

### ISSUE THREAD

**Issue by KonovalovMaxim** [gagliardetto/solana-go#30]
```
➜  slnc git:(main) ~/sdk/go1.16.5/bin/go run main.go serum get market HWHvQhFmJB3NUcu1aihKmrKegfVxBEHzwVX6yZCKEsi1
Error: fetch market: getting quote mint: required [1] byte, remaining [0]
Usage:
  cmd serum get market {market_addr} [flags]

Flags:
  -h, --help   help for market

Global Flags:
  -H, --http-header strings      HTTP header to add to JSON-RPC requests
      --kms-gcp-keypath string   Path to the cryptoKeys within a keyRing on GCP
  -u, --rpc-url string           API endpoint of eos.io blockchain node (default "http://api.mainnet-beta.solana.com")
      --vault-file string        Wallet file that contains encrypted key material (default "./solana-vault.json")

fetch market: getting quote mint: required [1] byte, remaining [0]
exit status 1
```
`HWHvQhFmJB3NUcu1aihKmrKegfVxBEHzwVX6yZCKEsi1` - its `SOL/USDT`

It seems that someting wrong with decoding USDT token info to token.Mint `GetAccountInfo(Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB) //USDT`

But its ok with some other tokens. With `Cm4MmknScg7qbKqytb1mM92xgDxv3TNXos4tKbBqTDy7` `RAY/SRM` market  it works fine.

am i doing something wrong?

**Comment by gagliardetto** [comment]
Hi! 

Try `go get github.com/gagliardetto/solana-go@be618d9fcf4cf6dec8138fed7875539f2e57202d`

The issue was: the optional params are encoded with a uint32 prefix (0 means the params is not set, 1 means that the param is set). This was erroneously done using a bool (uint8) instead of a uint32.

The issue was solved adding custom decoder/encoder methods (`UnmarshalWithDecoder` and `MarshalWithEncoder`) to the `token.Mint` struct.

---

NOTE: I still haven't started working on serum support; anything you'll find right now in solana-go for serum will be pretty limited and basic.
