### ISSUE TITLE
CreateProgramAddress working tests cases with Golang and TypeScript

### ISSUE THREAD

**Issue by cryptohazard** [gagliardetto/solana-go#33]
Hey,

I am trying to mirror the behaviour of a typescript lib for Solana. I need to use `CreateProgramAddress` to derive a Serum Market address. To have a working example I looked through the tests cases:
* https://github.com/gagliardetto/solana-go/blob/main/keys_test.go#L188
* https://github.com/solana-labs/solana-web3.js/blob/168d5e088edd48f9f0c1a877e888592ca4cfdf38/test/publickey.test.ts#L113

I see that the resulting addresses are different and I don't really understand why. I might be missing something. 
Any idea where the diff comes from? Do you by any chance have a example that work on both lib? 
I don't know Rust so I also don't know if there are tests cases on the original lib.

**Comment by gagliardetto** [comment]
Hey @cryptohazard 

Thanks for bringing this up!

> * https://github.com/gagliardetto/solana-go/blob/main/keys_test.go#L188

Those are the tests I ported from the Solana rust code. I now added a note: https://github.com/gagliardetto/solana-go/blob/3c4b307d5a9b95d5a74ab09e922ba9b2a766a064/keys_test.go#L189-L190

I now also ported the tests from the typescript you mentioned above, and they do correspond: https://github.com/gagliardetto/solana-go/blob/3c4b307d5a9b95d5a74ab09e922ba9b2a766a064/keys_test.go#L239-L242

My guess is that it's possible to visually confuse the both tests because the rust one uses `program_id := MustPublicKeyFromBase58("BPFLoaderUpgradeab1e11111111111111111111111")` and typescript uses `program_id := MustPublicKeyFromBase58("BPFLoader1111111111111111111111111111111111")` ( I spent a minute figuring out what was wrong too :sweat_smile: )

I also notice that the rust `create_program_address` ([here](https://github.com/solana-labs/solana/blob/216983c50e0a618facc39aa07472ba6d23f1b33a/sdk/program/src/pubkey.rs#L204)) removed the `if program_id.is_native_program_id()` check (see [latest here](https://github.com/solana-labs/solana/blob/390ef0fbcd000f5b1cd190913d4b5e3e19dabd56/sdk/program/src/pubkey.rs#L531)), so I removed it in my go implementation, too.

All this culminated in the release of `v1.0.4`.

See full changes diff: https://github.com/gagliardetto/solana-go/compare/v1.0.3...v1.0.4

**Comment by cryptohazard** [comment]
wow thank you.
I guess I really shouldn't code things like that in the middle of night 😅. 
I should now be able to finish my work here: https://github.com/teal-finance/rainbow/tree/psyoptions/pkg/provider/psyoptions
I learn a lot about Solana using your libs, especially with the examples. Thanks again!!

**Comment by gagliardetto** [comment]
:+1: 

> I should now be able to finish my work here: https://github.com/teal-finance/rainbow/tree/psyoptions/pkg/provider/psyoptions

Please remember that, when dealing with anchor-go, you need to keep the `UnmarshalWithDecoder` methods that get generated (otherwise you might not be able to decode the accounts data).

You also better use the `bin.NewBorshDecoder` instead of `bin.NewBinDecoder`.
