### ISSUE TITLE
getRecentBlockkhash

### ISSUE THREAD

**Issue by sparkycj328** [gagliardetto/solana-go#41]
With the json rpc api stating that getRecentBlockhash is deprecated and will no longer function on newer versions, will the solana.NewTransaction soon switch over to the updated getFeeForMessage?

**Comment by gagliardetto** [comment]
hi @sparkycj328 

I added the latest RPC methods in https://github.com/gagliardetto/solana-go/releases/tag/v1.3.0

Among those, you can find [GetLatestBlockhash](https://github.com/gagliardetto/solana-go#index--rpc--getlatestblockhash), which will be the new method to use instead of the `GetRecentBlockhash` method starting from Solana v1.9 (`GetRecentBlockhash` must still be used with `mainnet-beta` which AFAIK still runs solana v1.8).

**Comment by gagliardetto** [comment]
There was an error in the solana RPC documentation, for which I opened a PR: https://github.com/solana-labs/solana/pull/23190
